
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import sun.audio.AudioStream;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Cliente
 */
public class Urna extends javax.swing.JFrame {

    /**
     * Creates new form Urna
     */
    public Urna() {
        initComponents();
    }
    
    String num = "";
    String voto = "";
    String senha = "";
    String salvar = "salvar";
    int cand1=0;
    int cand2=0;
    int cand3=0;
    int nulo=0;
    int branco=0;
    int votantes=0;
    
    public void som () {
        try {
            AudioInputStream as =  AudioSystem.getAudioInputStream(new File ("C:/Urna.wav").getAbsoluteFile());
           
            try {
                Clip clip = AudioSystem.getClip();
                clip.open(as);
                clip.start();
            } catch (LineUnavailableException ex) {
                Logger.getLogger(Urna.class.getName()).log(Level.SEVERE, null, ex);
            }
         
        
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(Urna.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Urna.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
//    public void Som () {
//            try {
//                AudioInputStream as = AudioSystem.getAudioInputStream(new File ("C:/Urna.wav").getAbsoluteFile ());
//            } catch (UnsupportedAudioFileException ex) {
//                Logger.getLogger(Urna.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (IOException ex) {
//                Logger.getLogger(Urna.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        
//        
//        Clip clip;
//        try {
//            clip = AudioSystem.getClip();
//            clip.open(as);
//        } catch (LineUnavailableException ex) {
//            Logger.getLogger(Urna.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        
//        
//        catch (UnsupportedAudioFileException ex) {
//            Logger.getLogger(Urna.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (IOException ex) {
//            Logger.getLogger(Urna.class.getName()).log(Level.SEVERE, null, ex);
//        };
//        
//    }
    
    
    
    public void Limpar () {
        num = Num.getText();
        Num.setText("");
        Nome.setText("");
        Partido.setText("");
        Imagem.setText("");
        Imagem.setIcon(new ImageIcon());
        
        
            Botao1.setEnabled(true);
            Botao2.setEnabled(true);
            Botao3.setEnabled(true);
            Botao4.setEnabled(true);
            Botao5.setEnabled(true);
            Botao6.setEnabled(true);
            Botao7.setEnabled(true);
            Botao8.setEnabled(true);
            Botao9.setEnabled(true);
            Botao0.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Botao3 = new javax.swing.JButton();
        Botao1 = new javax.swing.JButton();
        Botao2 = new javax.swing.JButton();
        Botao4 = new javax.swing.JButton();
        Botao5 = new javax.swing.JButton();
        Botao6 = new javax.swing.JButton();
        Botao9 = new javax.swing.JButton();
        Botao8 = new javax.swing.JButton();
        Botao7 = new javax.swing.JButton();
        Botao0 = new javax.swing.JButton();
        BotaoB = new javax.swing.JButton();
        BotaoCo = new javax.swing.JButton();
        BotaoCon = new javax.swing.JButton();
        Imagem = new javax.swing.JLabel();
        Tipo = new javax.swing.JLabel();
        LNum = new javax.swing.JLabel();
        LNome = new javax.swing.JLabel();
        LPartido = new javax.swing.JLabel();
        Num = new javax.swing.JLabel();
        Nome = new javax.swing.JLabel();
        Partido = new javax.swing.JLabel();
        Senha = new javax.swing.JPasswordField();
        Senha1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        Botao3.setBackground(new java.awt.Color(102, 102, 102));
        Botao3.setText("3");
        Botao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao3ActionPerformed(evt);
            }
        });

        Botao1.setBackground(new java.awt.Color(102, 102, 102));
        Botao1.setText("1");
        Botao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao1ActionPerformed(evt);
            }
        });

        Botao2.setBackground(new java.awt.Color(102, 102, 102));
        Botao2.setText("2");
        Botao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao2ActionPerformed(evt);
            }
        });

        Botao4.setBackground(new java.awt.Color(102, 102, 102));
        Botao4.setText("4");
        Botao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao4ActionPerformed(evt);
            }
        });

        Botao5.setBackground(new java.awt.Color(102, 102, 102));
        Botao5.setText("5");
        Botao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao5ActionPerformed(evt);
            }
        });

        Botao6.setBackground(new java.awt.Color(102, 102, 102));
        Botao6.setText("6");
        Botao6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao6ActionPerformed(evt);
            }
        });

        Botao9.setBackground(new java.awt.Color(102, 102, 102));
        Botao9.setText("9");
        Botao9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao9ActionPerformed(evt);
            }
        });

        Botao8.setBackground(new java.awt.Color(102, 102, 102));
        Botao8.setText("8");
        Botao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao8ActionPerformed(evt);
            }
        });

        Botao7.setBackground(new java.awt.Color(102, 102, 102));
        Botao7.setText("7");
        Botao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao7ActionPerformed(evt);
            }
        });

        Botao0.setBackground(new java.awt.Color(102, 102, 102));
        Botao0.setText("0");
        Botao0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao0ActionPerformed(evt);
            }
        });

        BotaoB.setBackground(new java.awt.Color(255, 255, 255));
        BotaoB.setText("Branco");
        BotaoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoBActionPerformed(evt);
            }
        });

        BotaoCo.setBackground(new java.awt.Color(255, 51, 0));
        BotaoCo.setText("Corrigir");
        BotaoCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCoActionPerformed(evt);
            }
        });

        BotaoCon.setBackground(new java.awt.Color(0, 255, 0));
        BotaoCon.setText("Confirmar");
        BotaoCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoConActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Botao1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Botao2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Botao3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Botao4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Botao5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Botao6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Botao7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Botao8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Botao9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Botao0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BotaoB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoCo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoCon)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botao1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Botao3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Botao2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botao4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Botao5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Botao6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botao8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Botao7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Botao9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Botao0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoB, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoCo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoCon, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        Imagem.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        Imagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Imagem.setText("IMAGEM");
        Imagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Tipo.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        Tipo.setText("PRESIDENTE");

        LNum.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        LNum.setText("NÚMERO");

        LNome.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        LNome.setText("NOME");

        LPartido.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        LPartido.setText("PARTIDO");

        Num.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        Num.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Nome.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        Nome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Partido.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        Partido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Senha.setBackground(new java.awt.Color(102, 102, 102));
        Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaActionPerformed(evt);
            }
        });

        Senha1.setBackground(new java.awt.Color(102, 102, 102));
        Senha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Senha1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Visualizar");

        jLabel2.setText("Salvar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Tipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(Imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LNum)
                                    .addComponent(LPartido)
                                    .addComponent(LNome))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Num, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Partido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(Senha1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(Tipo))
                            .addComponent(Imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Num, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LNum))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LNome)
                            .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LPartido)
                            .addComponent(Partido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Senha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Botao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao3ActionPerformed
        num = Num.getText();
        Num.setText(num+"3");
        
        if (num.length()==1) {
            
            Botao1.setEnabled(false);
            Botao2.setEnabled(false);
            Botao3.setEnabled(false);
            Botao4.setEnabled(false);
            Botao5.setEnabled(false);
            Botao6.setEnabled(false);
            Botao7.setEnabled(false);
            Botao8.setEnabled(false);
            Botao9.setEnabled(false);
            Botao0.setEnabled(false);
            
            voto = Num.getText();
            
            if("11".equals(voto)){
                Imagem.setIcon(new ImageIcon("C:/Dilma.jpg"));
                Nome.setText("Dilminha");
                Partido.setText("PT");
            }
          
            else if("55".equals(voto)){
                Imagem.setIcon(new ImageIcon("C:/Aécio.jpg"));
                Nome.setText("AEZIO AUDITORE");
                Partido.setText("AC");
            }
            
            else if("45".equals(voto)){
                Imagem.setIcon(new ImageIcon("C:/marina.jpg"));
                Nome.setText("MARIA MARIA MARIA");
                Partido.setText("PEACE AND LOVE");
            }
        } else if (num.length() > 1) {
            Limpar();
        }
    }//GEN-LAST:event_Botao3ActionPerformed

    private void Botao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao1ActionPerformed
        num = Num.getText();
        Num.setText(num+"1");
        
        if (num.length()==1) {
            
            Botao1.setEnabled(false);
            Botao2.setEnabled(false);
            Botao3.setEnabled(false);
            Botao4.setEnabled(false);
            Botao5.setEnabled(false);
            Botao6.setEnabled(false);
            Botao7.setEnabled(false);
            Botao8.setEnabled(false);
            Botao9.setEnabled(false);
            Botao0.setEnabled(false);
            
            voto = Num.getText();
            
            if("11".equals(voto)){
                Imagem.setIcon(new ImageIcon("C:/Dilma.jpg"));
                Nome.setText("Dilminha");
                Partido.setText("PT");
            }
          
            else if("55".equals(voto)){
                Imagem.setIcon(new ImageIcon("C:/Aécio.jpg"));
                Nome.setText("AEZIO AUDITORE");
                Partido.setText("AC");
            }
            
            else if("45".equals(voto)){
                Imagem.setIcon(new ImageIcon("C:/marina.jpg"));
                Nome.setText("MARIA MARIA MARIA");
                Partido.setText("PEACE AND LOVE");
            }
            
        } else if (num.length() > 1) {
            Limpar();
        }
        
    }//GEN-LAST:event_Botao1ActionPerformed

    private void Botao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao2ActionPerformed
        num = Num.getText();
        Num.setText(num+"2");
        
        if (num.length()==1) {
            
            Botao1.setEnabled(false);
            Botao2.setEnabled(false);
            Botao3.setEnabled(false);
            Botao4.setEnabled(false);
            Botao5.setEnabled(false);
            Botao6.setEnabled(false);
            Botao7.setEnabled(false);
            Botao8.setEnabled(false);
            Botao9.setEnabled(false);
            Botao0.setEnabled(false);
            
            voto = Num.getText();
            
            if("11".equals(voto)){
                Imagem.setIcon(new ImageIcon("C:/Dilma.jpg"));
                Nome.setText("Dilminha");
                Partido.setText("PT");
            }
          
            else if("55".equals(voto)){
                Imagem.setIcon(new ImageIcon("C:/Aécio.jpg"));
                Nome.setText("AEZIO AUDITORE");
                Partido.setText("AC");
            }
            
            else if("45".equals(voto)){
                Imagem.setIcon(new ImageIcon("C:/marina.jpg"));
                Nome.setText("MARIA MARIA MARIA");
                Partido.setText("PEACE AND LOVE");
            }
        } else if (num.length() > 1) {
            Limpar();
        }
    }//GEN-LAST:event_Botao2ActionPerformed

    private void Botao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao4ActionPerformed
        num = Num.getText();
        Num.setText(num+"4");
        
        if (num.length()==1) {
            
            Botao1.setEnabled(false);
            Botao2.setEnabled(false);
            Botao3.setEnabled(false);
            Botao4.setEnabled(false);
            Botao5.setEnabled(false);
            Botao6.setEnabled(false);
            Botao7.setEnabled(false);
            Botao8.setEnabled(false);
            Botao9.setEnabled(false);
            Botao0.setEnabled(false);
            
            voto = Num.getText();
            
            if("11".equals(voto)){
                Imagem.setIcon(new ImageIcon("C:/Dilma.jpg"));
                Nome.setText("Dilminha");
                Partido.setText("PT");
            }
          
            else if("55".equals(voto)){
                Imagem.setIcon(new ImageIcon("C:/Aécio.jpg"));
                Nome.setText("AEZIO AUDITORE");
                Partido.setText("AC");
            }
            
            else if("45".equals(voto)){
                Imagem.setIcon(new ImageIcon("C:/marina.jpg"));
                Nome.setText("MARIA MARIA MARIA");
                Partido.setText("PEACE AND LOVE");
            }
        } else if (num.length() > 1) {
            Limpar();
        }
    }//GEN-LAST:event_Botao4ActionPerformed

    private void Botao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao5ActionPerformed
        num = Num.getText();
        Num.setText(num+"5");
        
        if (num.length()==1) {
            
            Botao1.setEnabled(false);
            Botao2.setEnabled(false);
            Botao3.setEnabled(false);
            Botao4.setEnabled(false);
            Botao5.setEnabled(false);
            Botao6.setEnabled(false);
            Botao7.setEnabled(false);
            Botao8.setEnabled(false);
            Botao9.setEnabled(false);
            Botao0.setEnabled(false);
            
            voto = Num.getText();
            
            if("11".equals(voto)){
                Imagem.setIcon(new ImageIcon("C:/Dilma.jpg"));
                Nome.setText("Dilminha");
                Partido.setText("PT");
            }
          
            else if("55".equals(voto)){
                Imagem.setIcon(new ImageIcon("C:/Aécio.jpg"));
                Nome.setText("AEZIO AUDITORE");
                Partido.setText("AC");
            }
            
            else if("45".equals(voto)){
                Imagem.setIcon(new ImageIcon("C:/marina.jpg"));
                Nome.setText("MARIA MARIA MARIA");
                Partido.setText("PEACE AND LOVE");
            }
        } else if (num.length() > 1) {
            Limpar();
        }
    }//GEN-LAST:event_Botao5ActionPerformed

    private void Botao6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao6ActionPerformed
        num = Num.getText();
        Num.setText(num+"6");
        
        if (num.length()==1) {
            
            Botao1.setEnabled(false);
            Botao2.setEnabled(false);
            Botao3.setEnabled(false);
            Botao4.setEnabled(false);
            Botao5.setEnabled(false);
            Botao6.setEnabled(false);
            Botao7.setEnabled(false);
            Botao8.setEnabled(false);
            Botao9.setEnabled(false);
            Botao0.setEnabled(false);
            
            voto = Num.getText();
            
            if("11".equals(voto)){
                Imagem.setIcon(new ImageIcon("C:/Dilma.jpg"));
                Nome.setText("Dilminha");
                Partido.setText("PT");
            }
          
            else if("55".equals(voto)){
                Imagem.setIcon(new ImageIcon("C:/Aécio.jpg"));
                Nome.setText("AEZIO AUDITORE");
                Partido.setText("AC");
            }
            
            else if("45".equals(voto)){
                Imagem.setIcon(new ImageIcon("C:/marina.jpg"));
                Nome.setText("MARIA MARIA MARIA");
                Partido.setText("PEACE AND LOVE");
            }
        } else if (num.length() > 1) {
            Limpar();
        }
    }//GEN-LAST:event_Botao6ActionPerformed

    private void Botao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao7ActionPerformed
        num = Num.getText();
        Num.setText(num+"7");
        
        if (num.length()==1) {
            
            Botao1.setEnabled(false);
            Botao2.setEnabled(false);
            Botao3.setEnabled(false);
            Botao4.setEnabled(false);
            Botao5.setEnabled(false);
            Botao6.setEnabled(false);
            Botao7.setEnabled(false);
            Botao8.setEnabled(false);
            Botao9.setEnabled(false);
            Botao0.setEnabled(false);
            
            voto = Num.getText();
            
            if("11".equals(voto)){
                Imagem.setIcon(new ImageIcon("C:/Dilma.jpg"));
                Nome.setText("Dilminha");
                Partido.setText("PT");
            }
          
            else if("55".equals(voto)){
                Imagem.setIcon(new ImageIcon("C:/Aécio.jpg"));
                Nome.setText("AEZIO AUDITORE");
                Partido.setText("AC");
            }
            
            else if("45".equals(voto)){
                Imagem.setIcon(new ImageIcon("C:/marina.jpg"));
                Nome.setText("MARIA MARIA MARIA");
                Partido.setText("PEACE AND LOVE");
            }
        } else if (num.length() > 1) {
            Limpar();
        }
    }//GEN-LAST:event_Botao7ActionPerformed

    private void Botao8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao8ActionPerformed
        num = Num.getText();
        Num.setText(num+"8");
        
        if (num.length()==1) {
            
            Botao1.setEnabled(false);
            Botao2.setEnabled(false);
            Botao3.setEnabled(false);
            Botao4.setEnabled(false);
            Botao5.setEnabled(false);
            Botao6.setEnabled(false);
            Botao7.setEnabled(false);
            Botao8.setEnabled(false);
            Botao9.setEnabled(false);
            Botao0.setEnabled(false);
            
            voto = Num.getText();
            
            if("11".equals(voto)){
                Imagem.setIcon(new ImageIcon("C:/Dilma.jpg"));
                Nome.setText("Dilminha");
                Partido.setText("PT");
            }
          
            else if("55".equals(voto)){
                Imagem.setIcon(new ImageIcon("C:/Aécio.jpg"));
                Nome.setText("AEZIO AUDITORE");
                Partido.setText("AC");
            }
            
            else if("45".equals(voto)){
                Imagem.setIcon(new ImageIcon("C:/marina.jpg"));
                Nome.setText("MARIA MARIA MARIA");
                Partido.setText("PEACE AND LOVE");
            }
        } else if (num.length() > 1) {
            Limpar();
        }
    }//GEN-LAST:event_Botao8ActionPerformed

    private void Botao9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao9ActionPerformed
        num = Num.getText();
        Num.setText(num+"9");
        
        if (num.length()==1) {
            
            Botao1.setEnabled(false);
            Botao2.setEnabled(false);
            Botao3.setEnabled(false);
            Botao4.setEnabled(false);
            Botao5.setEnabled(false);
            Botao6.setEnabled(false);
            Botao7.setEnabled(false);
            Botao8.setEnabled(false);
            Botao9.setEnabled(false);
            Botao0.setEnabled(false);
            
            voto = Num.getText();
            
            if("11".equals(voto)){
                Imagem.setIcon(new ImageIcon("C:/Dilma.jpg"));
                Nome.setText("Dilminha");
                Partido.setText("PT");
            }
          
            else if("55".equals(voto)){
                Imagem.setIcon(new ImageIcon("C:/Aécio.jpg"));
                Nome.setText("AEZIO AUDITORE");
                Partido.setText("AC");
            }
            
            else if("45".equals(voto)){
                Imagem.setIcon(new ImageIcon("C:/marina.jpg"));
                Nome.setText("MARIA MARIA MARIA");
                Partido.setText("PEACE AND LOVE");
            }
        } else if (num.length() > 1) {
            Limpar();
        }
    }//GEN-LAST:event_Botao9ActionPerformed

    private void Botao0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao0ActionPerformed
        num = Num.getText();
        Num.setText(num+"0");
        
        if (num.length()==1) {
            
            Botao1.setEnabled(false);
            Botao2.setEnabled(false);
            Botao3.setEnabled(false);
            Botao4.setEnabled(false);
            Botao5.setEnabled(false);
            Botao6.setEnabled(false);
            Botao7.setEnabled(false);
            Botao8.setEnabled(false);
            Botao9.setEnabled(false);
            Botao0.setEnabled(false);
            
            voto = Num.getText();
            
            if("11".equals(voto)){
                Imagem.setIcon(new ImageIcon("C:/Dilma.jpg"));
                Nome.setText("Dilminha");
                Partido.setText("PT");
            }
          
            else if("55".equals(voto)){
                Imagem.setIcon(new ImageIcon("C:/Aécio.jpg"));
                Nome.setText("AEZIO AUDITORE");
                Partido.setText("AC");
            }
            
            else if("45".equals(voto)){
                Imagem.setIcon(new ImageIcon("C:/marina.jpg"));
                Nome.setText("MARIA MARIA MARIA");
                Partido.setText("PEACE AND LOVE");
            }
        } else if (num.length() > 1) {
            Limpar();
        }
    }//GEN-LAST:event_Botao0ActionPerformed

    private void BotaoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoBActionPerformed
        num = Num.getText();
        Num.setText("Branco");
        Nome.setText("Branco");
        Partido.setText("Branco");
        Imagem.setIcon(new ImageIcon());
        Imagem.setText("Branco");
    }//GEN-LAST:event_BotaoBActionPerformed

    private void BotaoCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCoActionPerformed
        Limpar ();
    }//GEN-LAST:event_BotaoCoActionPerformed

    private void BotaoConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConActionPerformed
 
        votantes++;
        
        som();
        
        voto = Num.getText();
        if("11".equals(voto)){
            cand1++;
        } else if ("45".equals(voto)) {
            cand2++;
        } else if ("55".equals(voto)) {
            cand3++;
        } else if ("Branco".equals(voto)) {
            branco++;
        }else {
            nulo++;
        } 
        
        Limpar();
    }//GEN-LAST:event_BotaoConActionPerformed

    private void SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaActionPerformed
        
        senha = Senha.getText();
        
        if ("senha".equals(senha)){
        
        JOptionPane.showMessageDialog(null, 
                "##### RESULTADOS #####"
                + "\nVotantes: "+votantes
                + "\nCandidato 1: "+(cand1*100)/votantes+"%"
                + "\nCandidato 2: "+(cand2*100)/votantes+"%"
                + "\nCandidato 3: "+(cand3*100)/votantes+"%"
                + "\nBranco: "+(branco*100)/votantes+"%"
                + "\nNulo: "+(nulo*100)/votantes+"%");
        };
    }//GEN-LAST:event_SenhaActionPerformed

    private void Senha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Senha1ActionPerformed
        salvar = Senha1.getText();
        
        if ("salvar".equals(salvar)) {
            try {
                PrintWriter grava = new PrintWriter("C:/Resultados.txt");
                        grava.println("##### RESULTADOS #####");
                        grava.println("Votantes: "+votantes);
                        grava.println("Candidato 1: "+(cand1*100)/votantes+"%");
                        grava.println("Candidato 2: "+(cand2*100)/votantes+"%");
                        grava.println("Candidato 3: "+(cand3*100)/votantes+"%");
                        grava.println("Branco: "+(branco*100)/votantes+"%");
                        grava.println("Nulo: "+(nulo*100)/votantes+"%");
                        grava.close();
                        } catch (FileNotFoundException ex) {
                Logger.getLogger(Urna.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_Senha1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Urna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao0;
    private javax.swing.JButton Botao1;
    private javax.swing.JButton Botao2;
    private javax.swing.JButton Botao3;
    private javax.swing.JButton Botao4;
    private javax.swing.JButton Botao5;
    private javax.swing.JButton Botao6;
    private javax.swing.JButton Botao7;
    private javax.swing.JButton Botao8;
    private javax.swing.JButton Botao9;
    private javax.swing.JButton BotaoB;
    private javax.swing.JButton BotaoCo;
    private javax.swing.JButton BotaoCon;
    private javax.swing.JLabel Imagem;
    private javax.swing.JLabel LNome;
    private javax.swing.JLabel LNum;
    private javax.swing.JLabel LPartido;
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel Num;
    private javax.swing.JLabel Partido;
    private javax.swing.JPasswordField Senha;
    private javax.swing.JPasswordField Senha1;
    private javax.swing.JLabel Tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
