/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jokenpo;

import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Cliente
 */
public class Jokenpoo extends javax.swing.JFrame {

    /**
     * Creates new form Jokenpoo
     */
    public Jokenpoo() {
        initComponents();
    }
    
   
    int jp=0;
    int pg=0;
    int cg=0;
    int e=0;
    String nome="";
    int vezes=0;
    int cont=0;
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jogador = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Pedra = new javax.swing.JRadioButton();
        Papel = new javax.swing.JRadioButton();
        Tesoura = new javax.swing.JRadioButton();
        jogar = new javax.swing.JButton();
        cpu = new javax.swing.JLabel();
        jog = new javax.swing.JLabel();
        jogp = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jogc = new javax.swing.JLabel();
        result = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        emp = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fina = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jogador.setText("PLAYER");

        jLabel2.setText("CPU");

        buttonGroup2.add(Pedra);
        Pedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jokenpo/pedra.jpg"))); // NOI18N

        buttonGroup2.add(Papel);
        Papel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jokenpo/papel.jpg"))); // NOI18N

        buttonGroup2.add(Tesoura);
        Tesoura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jokenpo/tesoura.jpg"))); // NOI18N

        jogar.setText("JOGAR");
        jogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogarActionPerformed(evt);
            }
        });

        cpu.setText("0");

        jog.setText("0");

        jLabel3.setText("JOKENPO");

        jLabel4.setText("EMPATE");

        emp.setText("0");

        jButton1.setText("CONFIG");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fina)
                                .addGap(109, 109, 109)
                                .addComponent(jogar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(emp))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jogp, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jogc, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jogador)
                                        .addComponent(jog))
                                    .addGap(205, 205, 205)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cpu)
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Pedra)
                                            .addGap(18, 18, 18)
                                            .addComponent(Papel)))
                                    .addGap(18, 18, 18)
                                    .addComponent(Tesoura))))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jogador)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpu)
                    .addComponent(jog)
                    .addComponent(emp))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pedra)
                    .addComponent(Papel)
                    .addComponent(Tesoura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jogp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jogc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jogar)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(fina))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogarActionPerformed
        
        cont++;
        
        int num = (int) (Math.random()*3+1);
        
        if(Pedra.isSelected()) {
            jp=1;
        }else if(Papel.isSelected()) {
            jp=2;
        }else if(Tesoura.isSelected()) {
            jp=3;
        };
        
        
        
        if(jp==1 && num==3){
            pg = Integer.parseInt(jog.getText());
            pg = pg+1;
            jog.setText(""+pg);
            result.setText(nome+" GANHOU");
            jogp.setText(nome+": PEDRA");
            jogc.setText("CPU: TESOURA");
            }
        else if(jp==2 && num==1){
            pg = Integer.parseInt(jog.getText());
            pg = pg+1;
            jog.setText(""+pg);
            result.setText(nome+" GANHOU");
            jogp.setText(nome+": PAPEL");
            jogc.setText("CPU: PEDRA");
            }
        else if(jp==3 && num==2){
            pg = Integer.parseInt(jog.getText());
            pg = pg+1;
            jog.setText(""+pg);
            result.setText(nome+" GANHOU");
            jogp.setText(nome+": TESOURA");
            jogc.setText("CPU: PAPEL");
            }
        else if(jp==1 && num==2){
            cg = Integer.parseInt(cpu.getText());
            cg = cg+1;
            cpu.setText(""+cg);
            result.setText("CPU GANHOU");
            jogp.setText(nome+": PEDRA");
            jogc.setText("CPU: PAPEL");
            }
        else if(jp==2 && num==3){
            cg = Integer.parseInt(cpu.getText());
            cg = cg+1;
            cpu.setText(""+cg);
            result.setText("CPU GANHOU");
            jogp.setText(nome+": PAPEL");
            jogc.setText("CPU: TESOURA");
            }
        else if(jp==3 && num==1){
            cg = Integer.parseInt(cpu.getText());
            cg = cg+1;
            cpu.setText(""+cg);
            result.setText("CPU GANHOU");
            jogp.setText(nome+": TESOURA");
            jogc.setText("CPU: PEDRA");
            }
        else if(jp==1 && num==1){
            e = Integer.parseInt(emp.getText());
            e = e+1;
            emp.setText(""+e);
            result.setText("EMPATE");
            jogp.setText(nome+": PEDRA");
            jogc.setText("CPU: PEDRA");
            }
        else if(jp==2 && num==2){
            e = Integer.parseInt(emp.getText());
            e = e+1;
            emp.setText(""+e);
            result.setText("EMPATE");
            jogp.setText(nome+": PAPEL");
            jogc.setText("CPU: PAPEL");
            }
            else if(jp==3 && num==3){
            e = Integer.parseInt(emp.getText());
            e = e+1;
            emp.setText(""+e);
            result.setText("EMPATE");
            jogp.setText(nome+": TESOURA");
            jogc.setText("CPU: TESOURA");
            }
           
        if (cont==vezes) {
            JOptionPane.showMessageDialog(null,"Vitorias "+nome+": "+pg+" \n Vitorias CPU: "+cg+" \n Empates: "+e);
                if (cg>pg) {
                    JOptionPane.showMessageDialog(null,"CPU GANHOU, SEU AZARADO");
                }
                if (pg>cg) {
                    JOptionPane.showMessageDialog(null,"PARABÉNS "+nome+", VOCÊ GANHOU");
                }
                if (pg==cg) {
                    JOptionPane.showMessageDialog(null,"DEU EMPATE");
                }
            System.exit(0);
        }
           
    }//GEN-LAST:event_jogarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        nome = JOptionPane.showInputDialog("Entre com seu nome");
        vezes = Integer.parseInt(JOptionPane.showInputDialog("Quantas rodadas?"));
        jogador.setText(nome);
        emp.setText("0");
        cpu.setText("0");
        jog.setText("0"); 
        result.setText("");
        jogp.setText("");
        jogc.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jokenpoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jokenpoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jokenpoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jokenpoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jokenpoo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Papel;
    private javax.swing.JRadioButton Pedra;
    private javax.swing.JRadioButton Tesoura;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel cpu;
    private javax.swing.JLabel emp;
    private javax.swing.JLabel fina;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jog;
    private javax.swing.JLabel jogador;
    private javax.swing.JButton jogar;
    private javax.swing.JLabel jogc;
    private javax.swing.JLabel jogp;
    private javax.swing.JLabel result;
    // End of variables declaration//GEN-END:variables
}
